"""Initial migration.

Revision ID: dbac51c4e2b4
Revises: 
Create Date: 2020-05-01 00:21:59.892252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbac51c4e2b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_misc', sa.Column('bulk_items', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_misc', 'bulk_items')
    # ### end Alembic commands ###
